name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main  # 拉取源码分支
        submodules: true  # 递归拉取子模块

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # 根据你的需求调整版本
        cache: 'npm'  # 启用 npm 缓存加速

    - name: Install dependencies
      run: |
        npm install hexo-cli -g
        npm install

    - name: Inject Secrets into Config
      run: |
        # 检查模板文件是否存在
        if [ ! -f "_config.yml.template" ]; then
          echo "❌ Error: _config.yml.template missing!"
          exit 1
        fi
        # 替换占位符
        cp _config.yml.template _config.yml
        cp source/_scripts/gitalk-auto-init.js.template source/_scripts/gitalk-auto-init.js
        sed -i "s|__BAIDU_URL_SUBMIT_TOKEN__|${{ secrets.BAIDU_URL_SUBMIT_TOKEN }}|g" _config.yml
        sed -i "s|__GITALK_TOKEN__|${{ secrets.GITALK_TOKEN }}|g" source/_scripts/gitalk-auto-init.js
  
    - name: Generate static files
      run: |
        hexo clean
        hexo generate
        # 验证生成的 public 目录
        if [ ! -f "public/index.html" ]; then
          echo "❌ Error: Static files not generated!"
          exit 1
        fi

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public
    
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v3
